---
- name: Setup Apache with PHP and Timezone
  hosts: webservers
  become: yes

  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Add ondrej/php PPA
      apt_repository:
        repo: ppa:ondrej/php
        state: present
        update_cache: yes

    - name: Install Apache, PHP 8.1 and its Apache module
      apt:
        name:
          - apache2
          - php8.1
          - libapache2-mod-php8.1
        state: present
        update_cache: yes

    - name: Enable PHP 8.1 module
      command: a2enmod php8.1
      notify: Restart Apache

    - name: Remove default Apache index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Set timezone to Africa/Lagos
      timezone:
        name: Africa/Lagos

    - name: Create styled index.php showing current time
      copy:
        dest: /var/www/html/index.php
        content: |
          <?php
          date_default_timezone_set("Africa/Lagos");
          $current_time = date("F d, Y h:i:s A e");
          ?>
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>Welcome to Our Web Server</title>
            <style>
              body {
                background-color: #f0f8ff;
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                display: flex;
                flex-direction: column;
                align-items: center;
                justify-content: center;
                height: 100vh;
                margin: 0;
              }
              h1 {
                color: #2c3e50;
                font-size: 2.5em;
              }
              p {
                font-size: 1.3em;
                color: #34495e;
              }
              .time {
                margin-top: 20px;
                font-size: 1.5em;
                color: #27ae60;
              }
            </style>
          </head>
          <body>
            <h1>🎉 Welcome to Your Apache Web Server 🎉</h1>
            <p>This server is powered by Apache and PHP 8.1, deployed with Ansible.</p>
            <p class="time">Current Time: <?php echo $current_time; ?></p>
          </body>
          </html>

    - name: Ensure Apache is started and enabled
      systemd:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
